print('-------------------------')
print('Implementación Nahuel')
print('Implementación Nahuel')
print('Implementación Nahuel')
print('Implementación Nahuel')
print('Implementación Nahuel')
print('Implementación Nahuel')