print('-------------------------')
print('Implementación Gonzalo')
print('Implementación Gonzalo')
print('Implementación Gonzalo')
print('Implementación Gonzalo')
print('Implementación Gonzalo')
print('Implementación Gonzalo')