print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo')
print('hola mundo ya tengo git')